{"name": "test_last_commit_tensorflow", "status": "failed", "statusDetails": {"message": "AssertionError: assert 403 == 200\n +  where 403 = <Response [403]>.status_code", "trace": "def test_last_commit_tensorflow():\n        url = f\"{BASE_URL}/repos/tensorflow/tensorflow/commits\"\n        response = requests.get(url)\n>       assert response.status_code == 200\nE       assert 403 == 200\nE        +  where 403 = <Response [403]>.status_code\n\ntest/test_github_api.py:132: AssertionError"}, "start": 1760964512569, "stop": 1760964513102, "uuid": "9659b123-c00d-4f22-963b-995411c0b4c0", "historyId": "dea37e984f4b7d9a4cc8cd68f92c7af1", "testCaseId": "dea37e984f4b7d9a4cc8cd68f92c7af1", "fullName": "test.test_github_api#test_last_commit_tensorflow", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_github_api"}, {"name": "host", "value": "EU314602016234.local"}, {"name": "thread", "value": "5806-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_github_api"}], "titlePath": ["test", "test_github_api.py"]}